-- Scora Affiliate – Supabase schema
-- Run in Supabase SQL Editor

-- Tabel: profiles (één rij per gebruiker, gekoppeld aan auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null unique,
  role text not null check (role in ('admin', 'affiliate')) default 'affiliate',
  must_change_password boolean not null default true,
  created_at timestamptz not null default now()
);

-- Tabel: affiliates (maandcijfers per gebruiker)
create table if not exists public.affiliates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  month date not null,
  referrals_count integer not null default 0,
  unique (user_id, month)
);

-- Index voor snelle lookups
create index if not exists idx_affiliates_user_id on public.affiliates (user_id);
create index if not exists idx_affiliates_month on public.affiliates (month);

-- RLS inschakelen
alter table public.profiles enable row level security;
alter table public.affiliates enable row level security;

-- Policies: profiles – gebruiker leest/update alleen eigen rij
create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Insert voor profiles gebeurt via API met service role (admin create-user)

-- Policies: affiliates – gebruiker leest alleen eigen rijen
create policy "Users can read own affiliates"
  on public.affiliates for select
  using (auth.uid() = user_id);

-- Insert/update van affiliates doe je met de service role key (bijv. vanuit je hoofdapp bij nieuwe referrals)
